### ISSUE TITLE
Gebruik div elementen alleen voor styling

### ISSUE THREAD

**Issue by joostf** [jamilvice/Blok-Web-Jamil-Djabarkhan#1]
dit element kan beter in het formulier staan en een p element is hier beter:

https://github.com/jamilvice/Blok-Web-Jamil-Djabarkhan/blob/master/index.html#L27

**Comment by jamilvice** [comment]
Ik heb het in een p element veranderd en in het formulier gezet:

<form action="wowair_verhaal.html">

        <p class="jeboekzoeken">Je boek zoeken</p>
