### ISSUE TITLE
Formulier semantiek verbeteren

### ISSUE THREAD

**Issue by joostf** [jamilvice/Blok-Web-Jamil-Djabarkhan#4]
Verdeel je formulier in fieldsets met legends als heading

https://github.com/jamilvice/Blok-Web-Jamil-Djabarkhan/blob/master/index.html#L30-L35

**Comment by jamilvice** [comment]
Er zitten nu <div> in het formulier, omdat ik het anders niet geflexed krijg.

    <form action="wowair_verhaal.html">

        <p class="jeboekzoeken">Je boek zoeken</p>

       <h1>categorieën</h1>
        <div>

            <input type="button" value="Liefde" name="Liefde" />
            <input type="button" value="Fantasie" name="Liefde" />
            <input type="button" value="Actie" name="Liefde" />
            <input type="button" value="Horror" name="Liefde" />

        </div>
