### ISSUE TITLE
Zet headings altijd in de bijbehorende section

### ISSUE THREAD

**Issue by joostf** [jamilvice/Blok-Web-Jamil-Djabarkhan#5]
https://github.com/jamilvice/Blok-Web-Jamil-Djabarkhan/blob/master/index.html#L52-L55

**Comment by jamilvice** [comment]
Hier moet de heading wel boven de div, omdat de div geflexed is. Anders staan de h1 en div op dezelfde regel geflexed en dat wil ik niet. bijvoorbeeld:

<h1>categorieën</h1>
        <div>

            <input type="button" value="Liefde" name="Liefde" />
            <input type="button" value="Fantasie" name="Liefde" />
            <input type="button" value="Actie" name="Liefde" />
            <input type="button" value="Horror" name="Liefde" />

        </div>
