### ISSUE TITLE
Zet meta informatie in een footer of header

### ISSUE THREAD

**Issue by joostf** [jamilvice/Blok-Web-Jamil-Djabarkhan#6]
https://github.com/jamilvice/Blok-Web-Jamil-Djabarkhan/blob/master/index.html#L59

elk artikel kan een eigen footer en of header krijgen

**Comment by jamilvice** [comment]
Ik ga een header en footer in het artikel gebruiken om dingen te groeperen, bijvoorbeeld:

<article>
            <header><a href="wowair_verhaal.html"><img href="wowair_verhaal.html" src="fotos/verliefd%201.png" alt="verliefd"></a>
                <span>4 sterren</span></header>
            <footer>
                <h2>Verliefd</h2>
                <p class="tijdsduur">15 min</p>
            </footer>
        </article>
